print("Hello world")
print("Enter your firstname")
firstname = input()
print("Enter your lastname")
lastname = input()
age = input("Enter your age: ")
print(f"Szia {firstname} {lastname}! Your age is {age}.")
