print("Hello world")
print("Enter your firstname")
firstname = input()
print("Enter your lastname")
lastname = int(input())
age = input("Enter your age: ")
print(f"Hi {firstname} {lastname}! Your age is {age}.")

print(type(lastname))
print(type(age))
print(age + 2)
